stages:
  - build

build job:
  stage: build
  script:
    - export PYTHONPATH=.
    - export FLASK_APP=reporter.py
    - apt-get update
    - apt-get install -y python3-dev python3-pip
    - pip3 install --upgrade pip
    - pip3 install bcrypt
    - pip3 install -r requirements.txt
    - pytest
