image: python:latest

stages:
  - build

build job:
  stage: build
  script:
    - export PYTHONPATH=.
    - export FLASK_APP=reporter.py
    - pip install --upgrade pip
    - pip install bcrypt
    - pip install -r requirements.txt
    - pytest
