image: python:latest

stages:
  - build

build job:
  stage: build
  script:
    - export FLASK_APP=reporter.py
    - pip3 install --upgrade pip
    - pip3 install bcrypt
    - pip3 install -r requirements.txt
    - pytest
