image: python:latest

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate


stages:
  - build

build job:
  stage: build
  script:
    - export PYTHONPATH=.
    - export FLASK_APP=reporter.py
    - pip install --upgrade pip
    - pip install bcrypt
    - pip install -r requirements.txt
    - pytest
