"""empty message

Revision ID: 034f0f1632fc
Revises: 24391ef1d2d7
Create Date: 2021-09-20 21:01:36.226000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '034f0f1632fc'
down_revision = '24391ef1d2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading', 'Bid Price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading', 'Bid Price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
