"""removed permissions from roles

Revision ID: 0dc6f311a802
Revises: 92d2e994b354
Create Date: 2021-03-19 20:07:27.001109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dc6f311a802'
down_revision = '92d2e994b354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'permissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permissions', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
