"""empty message

Revision ID: 13c4b375f79a
Revises: eae8a2cd9858
Create Date: 2021-08-18 11:09:37.690626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13c4b375f79a'
down_revision = 'eae8a2cd9858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electricity_use')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricity_use',
    sa.Column('date_time', mysql.DATETIME(), nullable=True),
    sa.Column('electricity_use', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
