"""updated table name and columns

Revision ID: 216571f32ba4
Revises: af833ec69790
Create Date: 2021-09-16 00:48:38.179828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '216571f32ba4'
down_revision = 'af833ec69790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_power_generation',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('generator', sa.String(length=255), nullable=False),
    sa.Column('power', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date_time', 'generator'),
    sa.UniqueConstraint('date_time', 'generator')
    )
    op.drop_index('date_time', table_name='power_generation')
    op.drop_table('power_generation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('power_generation',
    sa.Column('date_time', mysql.DATETIME(), nullable=False),
    sa.Column('power', mysql.FLOAT(), nullable=True),
    sa.Column('device', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('temperature', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('date_time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('date_time', 'power_generation', ['date_time', 'device'], unique=False)
    op.drop_table('real_power_generation')
    # ### end Alembic commands ###
