"""added unique constraint to RolesUsers table

Revision ID: 219c1c74cac5
Revises: 7795ef076c1d
Create Date: 2021-03-31 19:21:54.302894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219c1c74cac5'
down_revision = '7795ef076c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles_users', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='unique')
    # ### end Alembic commands ###
