"""Added ELECTRICITY US

Revision ID: 234916db6939
Revises: 84fcbecd4744
Create Date: 2021-07-05 14:19:55.363982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '234916db6939'
down_revision = '84fcbecd4744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('electricity_use', 'date_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('electricity_use', 'date_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
