"""empty message

Revision ID: 24391ef1d2d7
Revises: 76d81c37d676
Create Date: 2021-09-20 19:53:00.310688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24391ef1d2d7'
down_revision = '76d81c37d676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading', 'Bid closing price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading', 'Bid closing price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
