"""renamed tables and added power gen bool

Revision ID: 28afb6ca9aac
Revises: 9e24d4e1d1cc
Create Date: 2021-09-16 01:37:11.616492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28afb6ca9aac'
down_revision = '9e24d4e1d1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_power_generation', sa.Column('power_generator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_power_generation', 'power_generator')
    # ### end Alembic commands ###
