"""added co2 table

Revision ID: 52408f5e567d
Revises: e6039a10bbdc
Create Date: 2021-05-21 15:48:18.407423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52408f5e567d'
down_revision = 'e6039a10bbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('co2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('co2',
    sa.Column('date_time', mysql.DATETIME(), nullable=False),
    sa.Column('co2', mysql.FLOAT(precision=255, scale=1, unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('date_time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
