"""empty message

Revision ID: 56a02a829d8f
Revises: e78aff590714
Create Date: 2021-03-14 00:50:33.753620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56a02a829d8f'
down_revision = 'e78aff590714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', sa.String(length=32), nullable=False))
    op.add_column('user', sa.Column('verified', sa.Boolean(), nullable=False))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'surname',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'surname',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_column('user', 'verified')
    op.drop_column('user', 'type')
    # ### end Alembic commands ###
