"""Updated user and role table for flask security

Revision ID: 682c22efeae2
Revises: aced2e22a83d
Create Date: 2021-03-17 17:32:07.335639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '682c22efeae2'
down_revision = 'aced2e22a83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('role', 'permissions',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.add_column('roles_users', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user', 'us_totp_secrets')
    op.drop_column('user', 'tf_phone_number')
    op.drop_column('user', 'us_phone_number')
    op.drop_column('user', 'tf_totp_secret')
    op.drop_column('user', 'tf_primary_method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tf_primary_method', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('tf_totp_secret', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('us_phone_number', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('tf_phone_number', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('us_totp_secrets', mysql.TEXT(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('roles_users', 'id')
    op.alter_column('role', 'permissions',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
