"""removed id from roles user and added multi table primary key

Revision ID: 738381efc37d
Revises: 0dc6f311a802
Create Date: 2021-03-20 11:44:21.697385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '738381efc37d'
down_revision = '0dc6f311a802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles_users', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('roles_users', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('roles_users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_users', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('roles_users', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('roles_users', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
