"""empty message

Revision ID: 76d81c37d676
Revises: 21d138d4483a
Create Date: 2021-09-20 19:51:31.102664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76d81c37d676'
down_revision = '21d138d4483a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading', sa.Column('Bid outcome', sa.Float(), nullable=True))
    op.drop_index('Date, time', table_name='trading')
    op.drop_column('trading', 'Bid outcome Volume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading', sa.Column('Bid outcome Volume', mysql.FLOAT(), nullable=True))
    op.create_index('Date, time', 'trading', ['Date, time'], unique=False)
    op.drop_column('trading', 'Bid outcome')
    # ### end Alembic commands ###
