"""user roles deleted on user or role delete

Revision ID: 7795ef076c1d
Revises: 738381efc37d
Create Date: 2021-03-20 12:03:54.059827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7795ef076c1d'
down_revision = '738381efc37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_users_ibfk_2', 'roles_users', type_='foreignkey')
    op.drop_constraint('roles_users_ibfk_1', 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.create_foreign_key('roles_users_ibfk_1', 'roles_users', 'role', ['role_id'], ['id'])
    op.create_foreign_key('roles_users_ibfk_2', 'roles_users', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
