"""updated trading tables

Revision ID: 8907dfe1418d
Revises: eefdb2658bbf
Create Date: 2021-10-19 13:37:17.025812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8907dfe1418d'
down_revision = 'eefdb2658bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clearout_price',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('Period', sa.Integer(), nullable=False),
    sa.Column('Bid closing price', sa.Float(), nullable=True),
    sa.Column('Volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date_time', 'Period')
    )
    op.create_table('predicted_price',
    sa.Column('Date, time', sa.DateTime(), nullable=False),
    sa.Column('Period', sa.Integer(), nullable=False),
    sa.Column('Predicted grid load(MWh)', sa.Float(), nullable=False),
    sa.Column('Predicted market price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('Date, time'),
    sa.UniqueConstraint('Date, time')
    )
    op.drop_index('Date, time', table_name='predicted_load')
    op.drop_table('predicted_load')
    op.add_column('trading', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.drop_index('Datetime', table_name='trading')
    op.create_unique_constraint(None, 'trading', ['date_time', 'Period'])
    op.drop_column('trading', 'Volume untraded')
    op.drop_column('trading', 'Datetime')
    op.drop_column('trading', 'Bid closing price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading', sa.Column('Bid closing price', mysql.FLOAT(), nullable=True))
    op.add_column('trading', sa.Column('Datetime', mysql.DATETIME(), nullable=False))
    op.add_column('trading', sa.Column('Volume untraded', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'trading', type_='unique')
    op.create_index('Datetime', 'trading', ['Datetime', 'Period'], unique=False)
    op.drop_column('trading', 'date_time')
    op.create_table('predicted_load',
    sa.Column('Date, time', mysql.DATETIME(), nullable=False),
    sa.Column('Period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Predicted grid load(MWh)', mysql.FLOAT(), nullable=False),
    sa.Column('Predicted market price', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('Date, time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('Date, time', 'predicted_load', ['Date, time'], unique=False)
    op.drop_table('predicted_price')
    op.drop_table('clearout_price')
    # ### end Alembic commands ###
