"""added timestamps to roles

Revision ID: 92d2e994b354
Revises: 682c22efeae2
Create Date: 2021-03-19 20:03:38.612236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d2e994b354'
down_revision = '682c22efeae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles_users', sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles_users', sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles_users', 'update_datetime')
    op.drop_column('roles_users', 'create_datetime')
    op.drop_column('role', 'create_datetime')
    # ### end Alembic commands ###
