"""added site table and added time stamps

Revision ID: 9e24d4e1d1cc
Revises: 216571f32ba4
Create Date: 2021-09-16 01:35:08.829899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e24d4e1d1cc'
down_revision = '216571f32ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_site_reading',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.add_column('real_power_generation', sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('real_power_generation', sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index('date_time', table_name='real_power_generation')
    op.drop_column('real_power_generation', 'generator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_power_generation', sa.Column('generator', mysql.VARCHAR(length=255), nullable=False))
    op.create_index('date_time', 'real_power_generation', ['date_time', 'generator'], unique=False)
    op.drop_column('real_power_generation', 'update_datetime')
    op.drop_column('real_power_generation', 'create_datetime')
    op.drop_table('real_site_reading')
    # ### end Alembic commands ###
