"""rename elctricity use table

Revision ID: a683af7ee05a
Revises: f64c62f21745
Create Date: 2021-07-06 21:18:12.130910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a683af7ee05a'
down_revision = 'f64c62f21745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elec_use',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('electricity_use', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.drop_table('e_use')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_use',
    sa.Column('date_time', mysql.DATETIME(), nullable=False),
    sa.Column('electricity_use', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('date_time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('elec_use')
    # ### end Alembic commands ###
