"""added relationship between co2 and elec usage

Revision ID: aa73e6cd5d62
Revises: a683af7ee05a
Create Date: 2021-07-31 14:33:34.314839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa73e6cd5d62'
down_revision = 'a683af7ee05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'co2', 'elec_use', ['date_time'], ['date_time'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'co2', type_='foreignkey')
    # ### end Alembic commands ###
