"""Added names to users

Revision ID: aced2e22a83d
Revises: 7cb67ec51bfc
Create Date: 2021-03-17 12:52:48.718279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aced2e22a83d'
down_revision = '7cb67ec51bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=128), nullable=False))
    op.add_column('user', sa.Column('surname', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'surname')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
