"""updated columns in power gen table

Revision ID: af833ec69790
Revises: b3d6c710aa26
Create Date: 2021-09-15 16:56:44.335825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af833ec69790'
down_revision = 'b3d6c710aa26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_generation', sa.Column('device', sa.String(length=255), nullable=False))
    op.add_column('power_generation', sa.Column('temperature', sa.Float(), nullable=True))
    op.drop_index('date_time', table_name='power_generation')
    op.create_unique_constraint(None, 'power_generation', ['date_time', 'device'])
    op.drop_column('power_generation', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_generation', sa.Column('location', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'power_generation', type_='unique')
    op.create_index('date_time', 'power_generation', ['date_time', 'location'], unique=False)
    op.drop_column('power_generation', 'temperature')
    op.drop_column('power_generation', 'device')
    # ### end Alembic commands ###
