"""adding the elec gener table

Revision ID: b3d6c710aa26
Revises: e81d737e838e
Create Date: 2021-09-15 15:24:00.704182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d6c710aa26'
down_revision = 'e81d737e838e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('power_generation',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('power', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date_time', 'location'),
    sa.UniqueConstraint('date_time', 'location')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('power_generation')
    # ### end Alembic commands ###
