"""added co2 table

Revision ID: bc6d06c013a1
Revises: b5378262047b
Create Date: 2021-06-20 11:38:38.831185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc6d06c013a1'
down_revision = 'b5378262047b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('co2',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('co2', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.drop_table('co2')
    # ### end Alembic commands ###
