"""empty message

Revision ID: cdd3cdd61f12
Revises: a683af7ee05a
Create Date: 2021-07-22 22:39:07.979667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd3cdd61f12'
down_revision = 'a683af7ee05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('Volume Traded', sa.Float(), nullable=True),
    sa.Column('Volume untraded', sa.Float(), nullable=True),
    sa.Column('Clearout Price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trading')
    # ### end Alembic commands ###
