"""updated elec_gen column

Revision ID: e81d737e838e
Revises: 34e14ce1bdb5
Create Date: 2021-09-01 13:39:16.057180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e81d737e838e'
down_revision = '34e14ce1bdb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elec_gen', sa.Column('wind_gen', sa.Float(), nullable=True))
    op.add_column('elec_gen', sa.Column('solar_gen', sa.Float(), nullable=True))
    op.drop_column('elec_gen', 'electricity_gen')
    op.drop_column('elec_gen', 'device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elec_gen', sa.Column('device', mysql.VARCHAR(length=5), nullable=True))
    op.add_column('elec_gen', sa.Column('electricity_gen', mysql.FLOAT(), nullable=True))
    op.drop_column('elec_gen', 'solar_gen')
    op.drop_column('elec_gen', 'wind_gen')
    # ### end Alembic commands ###
