"""added electricity use

Revision ID: f64c62f21745
Revises: bc6d06c013a1
Create Date: 2021-07-06 12:08:22.934817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f64c62f21745'
down_revision = 'bc6d06c013a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_use',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('electricity_use', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.drop_table('e_use')
    # ### end Alembic commands ###
