"""Adding trading table

Revision ID: f8704cc7bb08
Revises: cdd3cdd61f12
Create Date: 2021-07-31 11:15:07.337992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8704cc7bb08'
down_revision = 'cdd3cdd61f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading', sa.Column('Bid Price', sa.Float(), nullable=False))
    op.add_column('trading', sa.Column('Bid Units Volume(kWh)', sa.Float(), nullable=True))
    op.add_column('trading', sa.Column('Bid closing price', sa.Float(), nullable=False))
    op.add_column('trading', sa.Column('Bid outcome Volume', sa.Float(), nullable=True))
    op.add_column('trading', sa.Column('Bid type', sa.String(length=255), nullable=True))
    op.add_column('trading', sa.Column('Date, time', sa.DateTime(), nullable=False))
    op.add_column('trading', sa.Column('Imbalance Price', sa.Float(), nullable=True))
    op.add_column('trading', sa.Column('Imbalance volume', sa.Float(), nullable=True))
    op.add_column('trading', sa.Column('Net profit', sa.Float(), nullable=True))
    op.add_column('trading', sa.Column('Period', sa.Integer(), nullable=False))
    op.add_column('trading', sa.Column('Predicted grid load(MWh)', sa.Float(), nullable=False))
    op.add_column('trading', sa.Column('Predicted market price', sa.Float(), nullable=False))
    op.add_column('trading', sa.Column('Volume Generated onsite', sa.Float(), nullable=True))
    op.add_column('trading', sa.Column('Volume consumed onsite', sa.Float(), nullable=True))
    op.drop_column('trading', 'date_time')
    op.drop_column('trading', 'Clearout Price')
    op.drop_column('trading', 'Volume Traded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading', sa.Column('Volume Traded', mysql.FLOAT(), nullable=True))
    op.add_column('trading', sa.Column('Clearout Price', mysql.FLOAT(), nullable=True))
    op.add_column('trading', sa.Column('date_time', mysql.DATETIME(), nullable=False))
    op.drop_column('trading', 'Volume consumed onsite')
    op.drop_column('trading', 'Volume Generated onsite')
    op.drop_column('trading', 'Predicted market price')
    op.drop_column('trading', 'Predicted grid load(MWh)')
    op.drop_column('trading', 'Period')
    op.drop_column('trading', 'Net profit')
    op.drop_column('trading', 'Imbalance volume')
    op.drop_column('trading', 'Imbalance Price')
    op.drop_column('trading', 'Date, time')
    op.drop_column('trading', 'Bid type')
    op.drop_column('trading', 'Bid outcome Volume')
    op.drop_column('trading', 'Bid closing price')
    op.drop_column('trading', 'Bid Units Volume(kWh)')
    op.drop_column('trading', 'Bid Price')
    # ### end Alembic commands ###
